### ISSUE TITLE
Is it duplicated with forgelin？

### ISSUE THREAD

**Issue by forestbat** [ocpu/Boxlin#1]
https://minecraft.curseforge.com/projects/shadowfacts-forgelin

**Comment by ocpu** [comment]
Now that I have looked at Forgelin source code I can say we do really similar things. But that is quite inevitable since we both are language adapters for Kotlin. Though there are some things to note.

1. Making it a core mod is not needed since Kotlin is great for Java interop. The only thing I see Forgelin do with it being a core mod is load itself. 
  As of the time of writing you get a warning using Forgelin and it was created 6 of August this year. ([Forgelin issue](https://github.com/shadowfacts/Forgelin/issues/21))
3. Does not support you using instance factory methods. Not giving you all the flexibility you could use if you wanted.

Otherwise there arn't any big drawbacks using either mod when coding with Kotlin for forge. It is possible to not use any of our mods when building forge mods. You just have to use the syntax similar to how you code a java mod now.
