### ISSUE TITLE
Kotlin Coroutines Support

### ISSUE THREAD

**Issue by liketechnik** [ocpu/Boxlin#3]
Hey,
so first, great library. I think it's important that there's something like a common library mod all mods that are kotlin based use so we do not end up with a dependency hell :)
Then to my problem/question: I'd like to have Kotlin Coroutines support for my mod so I'd be able to use Kotlin's library for async tasks. Because it's still experimental it's not packed with kotlin, but in an extra library. Could you include this library ('org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.0-RC1') in the dependency block of the ```build.gradle```? If you want, I could also open up a pull request for that.

liketechnik

**Comment by liketechnik** [comment]
Oh, I forgot to include a link to the respective documentation/github project:
* [Official Kotlin Docs for Coroutines](https://kotlinlang.org/docs/reference/coroutines/coroutines-guide.html)
* [The GitHub repo](https://github.com/Kotlin/kotlinx.coroutines)

**Comment by ocpu** [comment]
This would be awesome to have and would be a good addition to the project. Since this dependency will probably be merged into Kotlin later it wont be a problem. If you care about the [Hacktoberfest](https://hacktoberfest.digitalocean.com) or you have time you can submit a PR for this. Otherwise I can include this. I am not at all opposed to having contributions through PR:s from other people. But having too many dependencies could be a bad thing in the long run.

**Comment by liketechnik** [comment]
Thanks for your quick response. Because I'm still having holidays till the end of the week I'll prepare a PR. Is there anything I should take special care of when adding the dependency?

**Comment by ocpu** [comment]
Only that the Minecraft client works to launch and does not have any errors except for any expected ones like not being able to connect to the authentication service.
